# Generated by Django 5.2.17 on 2026-08-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SIET Helpdesk', max_length=100)),
                ('from_email', models.EmailField(default='helpdesk@siet.edu.in', help_text='Default From email address', max_length=254)),
                ('smtp_backend', models.CharField(choices=[('smtp', 'Live SMTP (Sends real emails)'), ('console', 'Console / Development (Outputs to server log)')], default='console', help_text='Choose Live SMTP to send real emails to inboxes, or Console for dev/testing', max_length=50)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS (typically port 587)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL (typically port 465)')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='SMTP App Password', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Email Configuration',
            },
        ),
    ]
