# Generated by Django 5.2.17 on 2026-08-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_siteemailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteemailsetting',
            name='site_url',
            field=models.CharField(blank=True, default='', help_text='LAN or Public Base URL (e.g. http://10.10.10.141:8000). Auto-detects LAN IP if left blank.', max_length=255),
        ),
    ]
