# Generated by Django 5.2.17 on 2026-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('field_key', models.SlugField(max_length=80, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('radio', 'Radio buttons'), ('checkbox', 'Checkboxes'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='One option per line for radio, checkbox, or dropdown fields')),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
