# Generated by Django 5.2.17 on 2026-08-23 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_issueformfield_ticket_custom_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueformfield',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for category-specific questions. Leave empty to apply globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tickets.category'),
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📌', help_text='Emoji or icon representation', max_length=50)),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display this item on user dashboard homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category linked to this service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.category')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
