# Generated by Django 5.2.17 on 2026-08-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_issueformfield_category_servicecatalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueformfield',
            name='condition_field_key',
            field=models.CharField(blank=True, help_text='Parent question field key to check', max_length=80),
        ),
        migrations.AddField(
            model_name='issueformfield',
            name='condition_operator',
            field=models.CharField(choices=[('equals', 'Equals / Matches'), ('contains', 'Contains'), ('in', 'Is one of'), ('not_equals', 'Does not equal')], default='equals', max_length=20),
        ),
        migrations.AddField(
            model_name='issueformfield',
            name='condition_type',
            field=models.CharField(choices=[('always', 'Always visible'), ('visible_if', 'Visible if...'), ('hidden_if', 'Hidden if...')], default='always', max_length=20),
        ),
        migrations.AddField(
            model_name='issueformfield',
            name='condition_value',
            field=models.CharField(blank=True, help_text='Value that triggers this question (e.g. Network Issue, Other)', max_length=200),
        ),
        migrations.AddField(
            model_name='issueformfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Short guidance or description under question', max_length=255),
        ),
    ]
