# Generated by Django 5.2.17 on 2026-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_issueformfield_condition_field_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueformfield',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('equals', 'Equals / Matches'), ('contains', 'Contains'), ('in', 'Is one of'), ('not_equals', 'Does not equal')], default='equals', max_length=20),
        ),
        migrations.AlterField(
            model_name='issueformfield',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('always', 'Always visible'), ('visible_if', 'Visible if...'), ('hidden_if', 'Hidden if...')], default='always', max_length=20),
        ),
    ]
