# Generated by Django 5.2.17 on 2026-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_issueformfield_condition_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('radio', 'Radio buttons'), ('checkbox', 'Checkboxes'), ('select', 'Dropdown'), ('file', 'File upload')], default='text', max_length=20),
        ),
    ]
