# Generated by Django 5.2.17 on 2026-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_issueformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueformfield',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=5, help_text='Maximum allowed file size in Megabytes (MB)'),
        ),
    ]
