# Generated by Django 5.2.17 on 2026-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='icon',
            field=models.CharField(blank=True, default='📌', help_text='Emoji or icon representation', max_length=50),
        ),
    ]
